// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdHEppMMnLPhFPHjVH-CELDawf4G8HyiQ',
    appId: '1:325298018946:web:4e15658b3fb1a5f144329b',
    messagingSenderId: '325298018946',
    projectId: 'flutter-chat-app-34394',
    authDomain: 'flutter-chat-app-34394.firebaseapp.com',
    storageBucket: 'flutter-chat-app-34394.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_XpMX6A__iVFriVs3RAePAmvyqtWYMDg',
    appId: '1:325298018946:android:c36bdf1c1dffebec44329b',
    messagingSenderId: '325298018946',
    projectId: 'flutter-chat-app-34394',
    storageBucket: 'flutter-chat-app-34394.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNG16hGS0Zn0z0m-p2Lq2iDb1vV7Ym1QY',
    appId: '1:325298018946:ios:f1a0b6a068b388f544329b',
    messagingSenderId: '325298018946',
    projectId: 'flutter-chat-app-34394',
    storageBucket: 'flutter-chat-app-34394.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNG16hGS0Zn0z0m-p2Lq2iDb1vV7Ym1QY',
    appId: '1:325298018946:ios:f1a0b6a068b388f544329b',
    messagingSenderId: '325298018946',
    projectId: 'flutter-chat-app-34394',
    storageBucket: 'flutter-chat-app-34394.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdHEppMMnLPhFPHjVH-CELDawf4G8HyiQ',
    appId: '1:325298018946:web:2dd9ab760eca07ea44329b',
    messagingSenderId: '325298018946',
    projectId: 'flutter-chat-app-34394',
    authDomain: 'flutter-chat-app-34394.firebaseapp.com',
    storageBucket: 'flutter-chat-app-34394.firebasestorage.app',
  );

}